import { KEYBOARD_BUTTONS_CODES } from "./KeyboardButtonsCodes";

export const KEYBOARD_ROWS = [
  {
    id: 0,
    buttons: [KEYBOARD_BUTTONS_CODES.BACKQUOTE, KEYBOARD_BUTTONS_CODES.DIGIT_1, KEYBOARD_BUTTONS_CODES.DIGIT_2,
    KEYBOARD_BUTTONS_CODES.DIGIT_3, KEYBOARD_BUTTONS_CODES.DIGIT_4, KEYBOARD_BUTTONS_CODES.DIGIT_5, KEYBOARD_BUTTONS_CODES.DIGIT_6,
    KEYBOARD_BUTTONS_CODES.DIGIT_7, KEYBOARD_BUTTONS_CODES.DIGIT_8, KEYBOARD_BUTTONS_CODES.DIGIT_9, KEYBOARD_BUTTONS_CODES.DIGIT_0,
    KEYBOARD_BUTTONS_CODES.MINUS, KEYBOARD_BUTTONS_CODES.EQUAL, KEYBOARD_BUTTONS_CODES.BACKSPACE]
  },
  {
    id: 1,
    buttons: [KEYBOARD_BUTTONS_CODES.TAB, KEYBOARD_BUTTONS_CODES.KEY_Q, KEYBOARD_BUTTONS_CODES.KEY_W,
    KEYBOARD_BUTTONS_CODES.KEY_E, KEYBOARD_BUTTONS_CODES.KEY_R, KEYBOARD_BUTTONS_CODES.KEY_T,
    KEYBOARD_BUTTONS_CODES.KEY_Y, KEYBOARD_BUTTONS_CODES.KEY_U, KEYBOARD_BUTTONS_CODES.KEY_I,
    KEYBOARD_BUTTONS_CODES.KEY_O, KEYBOARD_BUTTONS_CODES.KEY_P, KEYBOARD_BUTTONS_CODES.BRACKET_LEFT,
    KEYBOARD_BUTTONS_CODES.BRACKET_RIGHT, KEYBOARD_BUTTONS_CODES.BACKSLASH]
  },
  {
    id: 2,
    buttons: [KEYBOARD_BUTTONS_CODES.CAPSLOCK, KEYBOARD_BUTTONS_CODES.KEY_A, KEYBOARD_BUTTONS_CODES.KEY_S,
    KEYBOARD_BUTTONS_CODES.KEY_D, KEYBOARD_BUTTONS_CODES.KEY_F, KEYBOARD_BUTTONS_CODES.KEY_G,
    KEYBOARD_BUTTONS_CODES.KEY_H, KEYBOARD_BUTTONS_CODES.KEY_J, KEYBOARD_BUTTONS_CODES.KEY_K,
    KEYBOARD_BUTTONS_CODES.KEY_L, KEYBOARD_BUTTONS_CODES.SEMICOLON, KEYBOARD_BUTTONS_CODES.QUOTE,
    KEYBOARD_BUTTONS_CODES.ENTER]
  },
  {
    id: 3,
    buttons: [KEYBOARD_BUTTONS_CODES.SHIFT_LEFT, KEYBOARD_BUTTONS_CODES.KEY_Z, KEYBOARD_BUTTONS_CODES.KEY_X,
    KEYBOARD_BUTTONS_CODES.KEY_C, KEYBOARD_BUTTONS_CODES.KEY_V, KEYBOARD_BUTTONS_CODES.KEY_B, KEYBOARD_BUTTONS_CODES.KEY_N,
    KEYBOARD_BUTTONS_CODES.KEY_M, KEYBOARD_BUTTONS_CODES.COMMA, KEYBOARD_BUTTONS_CODES.PERIOD,
    KEYBOARD_BUTTONS_CODES.SLASH, KEYBOARD_BUTTONS_CODES.ARROW_UP, KEYBOARD_BUTTONS_CODES.SHIFT_RIGHT]
  },
  {
    id: 4,
    buttons: [KEYBOARD_BUTTONS_CODES.CONTROL_LEFT, KEYBOARD_BUTTONS_CODES.META, KEYBOARD_BUTTONS_CODES.ALT_LEFT,
    KEYBOARD_BUTTONS_CODES.SPACE, KEYBOARD_BUTTONS_CODES.ARROW_RIGHT, KEYBOARD_BUTTONS_CODES.CONTROL_RIGHT,
    KEYBOARD_BUTTONS_CODES.ALT_LEFT, KEYBOARD_BUTTONS_CODES.ARROW_DOWN, KEYBOARD_BUTTONS_CODES.ALT_RIGHT]
  }
]